server:
  port: 56711
  #servlet:
  #  context-path: /kytms-business

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  application:
    name: jwxt-business #指定服务名

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 50000

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#  mapper-locations: classpath:com/kytms/*/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:56798/eureka/,http://localhost:56702/eureka/
  instance:
    prefer-ip-address: true
    instance-id: system8083 #在注册中心页面显示的微服务名
